repos:
  - repo: local
    hooks:
      - id: check-path-names
        name: check path names
        entry: python scripts/check_path_names.py
        language: system
        pass_filenames: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
